### ISSUE TITLE
JS / CSS missing in repo

### ISSUE THREAD

**Issue by cobookman** [googlecodelabs/tools#19]
codelab.js and codelab.css is missing from the repo. The built html files link against them.

**Comment by x1ddos** [comment]
Hey @cobookman. The reason those are missing is because `claat` tool just spits out a default format but it can easily changed to something else using `-f <fmt>` option, where `<fmt>` may be any local file name.

In that case, with a custom format, any JS or CSS files we would provide are irrelevant. Although, it might not be a bad idea to include them for the default format, since the `claat` tool does provide it. So maybe we should actually include it.

Meanwhile, we have a public mailing list where I tried to summaries how the coupling of an HTML template with JS/CSS files works here:
https://groups.google.com/d/msg/codelab-authors/Vm2bSNOrRD0/v35wCPEBBgAJ

**Comment by x1ddos** [comment]
There's now `claat serve` command. I think it covers this use case. Reopen otherwise.
https://github.com/googlecodelabs/tools/releases/tag/v1.0.0
