### ISSUE TITLE
claat - Out-Of-Band (OOB) flow

### ISSUE THREAD

**Issue by djuang1** [googlecodelabs/tools#793]
https://developers.google.com/identity/protocols/oauth2/resources/oob-migration

Hi, I'm running into the Out-Of-Band (OOB) flow issue when I run `claat export <id>`. Is there a fix for this issue?

**Comment by mco-gh** [comment]
Sorry about this, the oauth flow claat is using has been [deprecated for security reasons](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration). I'll try to fix this when I get a chance but I don't currently have an ETA. 

Can't think of a work around for this because if claat can't access your docs, it can't export the codelab.

**Comment by mco-gh** [comment]
I think I have a [fix](https://github.com/googlecodelabs/tools/pull/798) for this now. I'll follow up here once it's merged.

**Comment by OrcaV** [comment]
Hi thanks @mco-gh, just to confirm if I get this right.
1. I check out your branch `authfix`.
2. `cd tools/claat`.
3. `go build .` to create `claat`.
4. `claat export GOOGLE_DOC_ID` (e.g. `claat export 1E6XMcdTexh5O8JwGy42SY3Ehzi8gOfUGiqTiUX6N04o`, from https://docs.google.com/document/d/1E6XMcdTexh5O8JwGy42SY3Ehzi8gOfUGiqTiUX6N04o/edit).
5. Then I get `https://accounts.google.com/o/oauth2/auth?...........`
6. Copy & Paste the above to a web browser.
7. I still get `Error 400: invalid_request`.

**Comment by OrcaV** [comment]
Sorry please ignore me, it works!!! thanks a lot. I mistakenly use the wrong `claat` instance.

**Comment by mco-gh** [comment]
np and good catch for anyone who tries this before the PR is merged - you'll want to use the version you built locally under bin/claat.

**Comment by mco-gh** [comment]
fixed in v2.2.5
